# Generated by Django 5.0.6 on 2024-07-13 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("payment_reference", models.CharField(max_length=100)),
                ("billing_name", models.CharField(max_length=255)),
                ("billing_address", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(max_length=50)),
                ("card_last4", models.CharField(max_length=4)),
                ("card_type", models.CharField(max_length=20)),
                
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
