# Generated by Django 5.0.6 on 2024-07-10 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceLocations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_city", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("capacity", models.IntegerField()),
                ("availability", models.BooleanField(default=True)),
                (
                    "price_per_hour",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("car_type", models.CharField(max_length=50)),
                ("car_image", models.CharField(max_length=255)),
                (
                    "default_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="cars.servicelocations",
                    ),
                ),
            ],
        ),
    ]
