# Generated by Django 5.0.6 on 2024-07-10 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_management", "0002_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="valid_until",
            field=models.DateField(default=datetime.date(2024, 7, 10)),
            preserve_default=False,
        ),
    ]
