# Generated by Django 5.0.6 on 2024-07-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_management", "0004_rename_coupon_coupons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmanagement",
            name="latest_available_date",
            field=models.DateTimeField(),
        ),
    ]
