# Generated by Django 5.0.6 on 2024-07-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_management", "0005_alter_stockmanagement_latest_available_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupons",
            name="valid_until",
            field=models.DateTimeField(),
        ),
    ]
