# Generated by Django 5.0.6 on 2024-07-12 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="dropoff_time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
