# Generated by Django 5.0.6 on 2024-07-12 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_booking_dropoff_time_booking_pickup_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="dropoff_date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="dropoff_time",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="pickup_date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="pickup_time",
        ),
        migrations.AddField(
            model_name="booking",
            name="dropoff_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
