# Generated by Django 5.0.6 on 2024-07-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_remove_booking_dropoff_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_status",
            field=models.BooleanField(default=True),
        ),
    ]
