# Generated by Django 5.0.6 on 2024-07-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_booking_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_time",
            field=models.DateField(auto_now=True),
        ),
    ]
