# Generated by Django 5.0.6 on 2024-07-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0005_booking_booking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
