# Generated by Django 5.0.6 on 2024-07-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0006_alter_booking_booking_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancellation_time",
            field=models.DateTimeField(null=True),
        ),
    ]
